apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test-webserver
  labels:
    name: ambassador-test
spec:
  containers:
  - name: nginx
    image: nginx:stable
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ambassadpr-test-svc
spec:
  selector:
    app: ambassador-test
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP


