version: '3.9'

services:
  proxy:
    build: ./
    networks:
      - example1
      - example2
    ports:
      - 80:80
      - 443:443

networks:
  example1:
    external:
      name: site01_default

  example2:
    external:
      name: site02_default
