USER-SUPPLIED VALUES:
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: https://hooks.slack.com/services/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
    receivers:
    - name: "null"
    - name: slack-notifications
    route:
      receiver: slack-notifications
    send_resolved: true
    slack_configs:
    - channel: '#alerts'
grafana:
  additionalDataSources:
  - name: loki
    type: loki
    url: http://loki.observability.svc.cluster.local:3100
  - name: tempo
    type: tempo
    url: http://tempo.observability.svc.cluster.local:3100
kubeControllerManager:
  endpoints:
  - 192.168.50.130
kubeScheduler:
  endpoints:
  - 192.168.50.130
