version: '3.9'
services:
  registry:
    image: rogal/apigee-registry
    ports:
      - "8080:8080"
    environment:
      REGISTRY_DATABASE_DRIVER: postgres
      REGISTRY_DATABASE_CONFIG: "host=db port=5432 user=apigee dbname=apigee password=apigee sslmode=disable"
    links:
      - postgres:db
  postgres:
    restart: always
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      DEBUG:  'true'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      APP_DB_USER: apigee
      APP_DB_PASS: apigee
      APP_DB_NAME: apigee
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
