version: '3.9'
services:
  registry:
    image: rogal/apigee-registry
    ports:
      - "8080:8080"
    environment:
      REGISTRY_DATABASE_DRIVER: postgres
      REGISTRY_DATABASE_CONFIG: "host=db port=5432 user=${POSTGRES_USER} dbname=apigee password=${POSTGRES_PASSWORD} sslmode=disable"
    links:
      - postgres:db
  postgres:
    restart: always
    image: postgres
    ports:
        - "5432:5432"
    environment:
        DEBUG:  'true'
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: db
    volumes: 
        - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
