---
- hosts: all
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    host_user: "vagrant"

  tasks:
    - name: make sure the system encoding is utf-8
      become: yes
      template:
        src: templates/locale
        dest: /etc/default/locale
        owner: root
        group: root
        mode: 0644

    # - include: tasks/prometheus.yml
