version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lab01-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8r8imkp01yb7"
s3_prefix = "lab01-python"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
