# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-lab
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    # availabilityZones: ["us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f"] # use single AZ to optimise data transfer between instances
