apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCOrTkJXZJxgxg8SQbrCrVdnLgm2gPm6iEEXsAc1NXABrkO+JL1ARjHPNojO07yzt7YFdt9XtCG5kaewdhZxeJl7bzDHusE83sRYE44eoAIfvp2DgLVCMi2SMk5UFkY0solbDXaXZllbbBcsPcwDHw4p+S0G8bfCL4YztZj+vmls4BWN6CH6kX/xJvegmoNVem5SIG3nwITL2Jvci3GcFAKpMk/ovjOGWdPtbzH3f/W8cz2YBd1YAWejTzB3c60Str0gYNDJeWNjinx8iDnRc4LAcLc7mGXY/IhlHNehg28MkyNxYBcpWYYu//Imva389d0LpS+r6fNNrIOJf4zZ2EiPvUwYrMSiGosVXUSDDywFFlFtckzFyTubq5nf6Z9wkHKaOdUcMMHpWFI3HY/TZYVLkbuOYoM/UURB8mmUI4S/bQ2YqaziNewP/GL+sYsJn3mQdQV/IWQ6cNEwdoG4wKiL4I4JX6+vvIOn5tw6cmqiBuizu3+T4B7IKh7os4VVgqZiO1YUvTVGNlCRiH1t1qEu+fE+BmtUJZhGO5YjA8ndIffFFePzxv0SJDYFyluTrnZPzBbdS9MEEeTfaEk26a7P1WdCj5uLpjBq12wN6lkAW++b5WrhVssL/FEbCn7rXMCUVMcyU6I23R32ekl9nBBKfO1QatYq3dh5MH9OU1m1bn4VLH/H3l6nrP6Hk60Q7u+ih5PgXlu
    username: AgApMkHvQP6MBK0ljRuKxZDetTDWZWT93A0XIfPLocB7VpjKzgxcsOkcIbOIC+K4Jt7WhnLNdozMIyNWjEfHcJzgTrkJ7lJGhyHi+fdfFZr+W7SB5wBxErqOMVuEadtnNr9Tos9ubXjV7DrhchzWrjTvqBQgHvYpbzFCHeL80g3TKxD3YknLuMx7P5lx4/GD1pOAExWQxLJcxM+aQt4LP0h9xkL7iN/Cr6ItwwjQ/EvEAj09w4y084JzlA2yZvAlcxDyuS0xfxWbbh3USMgTxV0z/hjjM1DY8hWBAJsNprmtwUQ5IdXVL9Q9j1blE76PJsfyplaHWlmE8vwvS29W8KI9vV84uws/ppONNGb0Ah61BPOAdKe67qdV0RO9J61HHJq9yc0sv1oG15m7rc+bgRixc6uzSs5MCJjbQn0/SlFKsBuqG8CjTrsRhU3rtLYoFuqzhjwve7PbjhlzKlq4LEWJuguZuvixpkYKuJ0gYITj/Kv/UydsTEDPfKCYJKJx3U5S3mEsYs+i+QhXPmafgyQgYdF9P6olJNBGTm0Z1MqOCq4CE+GZmU41cy0SfQsuqQfKek+cyHmc1teZ9GgqvW0gPHrrGQZZ7TRpStxnNhchLZoLsX/zzeBULJC0aYO4hSeB9cGAHq1aBVgqGHxmzbIi8C3F0y7FkEzQJzW8FBYaFtLwiHZj6KKyP0D30oWmvp/PEW+aOehm4g==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

