global:
  resolve_timeout: 5m
  smtp_require_tls: false

route:
  receiver: 'email'
  routes:
    - match:
        severity: 'critical'
receivers:
- name: 'email'
  email_configs:
    - to: 'alerts@ftapp.io'
      from: 'prometheus@email.com'
      smarthost: localhost:1025
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
