---
- name: Enable addons
  become: yes
  command: microk8s enable rbac dns metrics-server hostpath-storage registry
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - "'This MicroK8s addons failed.' not in mk8sstatusout.stdout_lines"
      - mk8sstatusout.rc > 0

# - name: add helm repository to user
#   become: yes
#   become_user: '{{ item.0 }}'
#   shell: "microk8s.helm repo add {{ item.1.name }} {{ item.1.url }}"
#   args:
#     executable: /bin/bash
#   changed_when: true
#   with_nested:
#     - "{{ users }}"
#     - "{{ helm3_repositories }}"

# - name: update helm repos
#   become: yes
#   become_user: '{{ user }}'
#   shell: "microk8s.helm repo update"
#   args:
#     executable: /bin/bash
#   changed_when: true
#   with_items: '{{ users }}'
#   loop_control:
#     loop_var: user
#     label: '{{ user }}'
