- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true    

# - name: Install Docker Module for Python
#   pip:
#     name: docker

# sudo groupadd docker
# sudo usermod -aG docker $USER
# newgrp docker
# docker run hello-world

# ```
# sudo mkdir -p /var/snap/microk8s/current/args/certs.d/10.141.241.175:32000
# sudo touch /var/snap/microk8s/current/args/certs.d/10.141.241.175:32000/hosts.toml
# ```


# ```
# # /var/snap/microk8s/current/args/certs.d/10.141.241.175:32000/hosts.toml
# server = "http://10.141.241.175:32000"

# [host."http://10.141.241.175:32000"]
# capabilities = ["pull", "resolve"]
# ```
