apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.14
    chart: postgresql
    helm:
      parameters:
        - name: global.storageClass
          value: microk8s-hostpath
        - name: image.tag
          value: 15.4.0
        - name: primary.persistence.size
          value: 20Gi
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
