alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
rbac:
  create: false
server:
  name: server
  service:
    type: NodePort
