version: '3.9'
services:
  postgres:
    restart: always
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      DEBUG:  'true'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      APP_DB_USER: userdb
      APP_DB_PASS: userdb
      APP_DB_NAME: userdb
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
