version: '3.9'
services:
  postgres:
    restart: always
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      DEBUG:  'true'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      APP_DB_USER: userdb
      APP_DB_PASS: userdb
      APP_DB_NAME: userdb
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/

  minio:
    image: quay.io/minio/minio:RELEASE.2022-07-26T00-53-03Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - "9000"
      - "9001"
    # environment:
    #   MINIO_ROOT_USER: minioadmin
    #   MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-data:
  db:
    driver: local  
