- job_name: 'minio-job'
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: 
    - minio:9000
- job_name: 'argocd-metrics'
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: 
    - argocd-metrics.argocd.svc.cluster.local:8082
- job_name: 'argocd-server-metrics'
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: 
    - argocd-server-metrics.argocd.svc.cluster.local:8083
