apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-query
  name: thanos-query
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 10902
    targetPort: http
    nodePort: 32432
  selector:
    app.kubernetes.io/name: thanos-query
