apiVersion: v1
kind: ConfigMap
metadata:
  name: objstore
data:
  objstore: |
    type: S3
    config:
      bucket: thanos
      endpoint: http://minio:9000
      access_key: JTTUHe73iYPR8gQveFdz
      secret_key: QIe0e2Cqdp6YuCfTE28oxKkZ95JjKBrchAOxCla0
      insecure: true
